version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: java-stats-server
    container_name:
      stats_server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DB_NAME=stats
      - POSTGRES_USER=statsAdm
      - POSTGRES_PASSWORD=changeme
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name:
      stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsAdm
      - POSTGRES_PASSWORD=changeme

  ewm-service:
    build: ./main-service
    image: java-main-service
    container_name:
      main_service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name:
      ewm_db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewmAdm
      - POSTGRES_PASSWORD=changeme
