-- DROP TABLE IF EXISTS stats;


create TABLE IF NOT EXISTS stats
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    created timestamp without time zone,
    CONSTRAINT pk_stat PRIMARY KEY (id)
    );